### ISSUE TITLE
Use micromachine to manage state

### ISSUE THREAD

**Issue by jonallured** [artsy/stress#16]
On Bearden I had a great experience using https://github.com/soveran/micromachine to manage the state in that application and I think it would be useful here in Stress. The pattern I used in Bearden was for the model to instantiate the machine and then provide methods to trigger state transitions with optional background jobs for side effects:

https://github.com/artsy/bearden/blob/master/app/models/import.rb

Then the actual machine class is where the states are setup and the valid transitions are defined:

https://github.com/artsy/bearden/blob/master/app/models/import_micro_machine.rb

**Comment by ashkan18** [comment]
have you used https://github.com/aasm/aasm before? looking at it's usage and https://medium.com/geogo-in/state-machines-in-rails-5-45259a4f42da looks like it does some of the stuff with some helper methods for us already, I'm interested mostly in `may_<state>?` method and actual setting it with `<state>!`.

**Comment by jonallured** [comment]
I confess that I have not used AASM before, but I have heard from other devs that it's big and unwieldy. What I liked about micromachine was that it was just one Ruby file and extremely easy to read and reason about.
